/** Cloud ids from https://ollama.com/api/tags plus family aliases. Refreshed 2026-08-20. */
export const OLLAMA_CLOUD_MODELS = [
  "kimi-k3",
  "glm-5.2",
  "kimi-k2.7-code",
  "nemotron-3-ultra",
  "minimax-m3",
  "deepseek-v4-flash:0731",
  "deepseek-v4-flash:preview",
  "deepseek-v4-flash",
  "deepseek-v4-pro:0813",
  "deepseek-v4-pro:preview",
  "deepseek-v4-pro",
  "glm-5.1",
  "kimi-k2.6",
  "minimax-m2.7",
  "gemma4:31b",
  "gemma4:cloud",
  "nemotron-3-super",
  "qwen3.5:397b",
  "qwen3.5:cloud",
  "nemotron-3-nano:30b",
  "mistral-large-3:675b",
  "gpt-oss:120b",
  "gpt-oss:20b",
] as const;

export const OLLAMA_LOCAL_MODELS = [
  "llama3.2",
  "llama3.1",
  "mistral",
  "qwen2.5",
  "qwen3.5",
  "gemma4",
  "phi4",
  "kimi-k3-cloud",
  "glm-5.2-cloud",
  "kimi-k2.7-code-cloud",
  "nemotron-3-ultra-cloud",
  "minimax-m3-cloud",
  "deepseek-v4-flash-cloud",
  "deepseek-v4-pro-cloud",
  "glm-5.1-cloud",
  "kimi-k2.6-cloud",
  "minimax-m2.7-cloud",
  "gemma4:31b-cloud",
  "nemotron-3-super-cloud",
  "qwen3.5:397b-cloud",
  "nemotron-3-nano:30b-cloud",
  "mistral-large-3:675b-cloud",
  "gpt-oss:120b-cloud",
  "gpt-oss:20b-cloud",
] as const;
